baseURL = "https://www.insignificantgamer.blog/"
languageCode = 'en-us'
title = 'Insignificant Gamer'
theme = 'rusty-typewriter'

[params]
  description = "Musings of an Insignificant Lifetime Gamer"

[params.author]
  name = "Just_Irish / Sean R."
  email = "justirish.insignificant@proton.me"

[params.rtwt]
  sidePane = true
  countPageItems = 20
  searchPath = 'search'

[params.rtwt.home]
  showBio = true
  showAuthorImg = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5

[params.rtwt.side.home]
  sidePaneSticky = false
  taxonomies = ['tags']
  countTaxonomy = 5

[params.rtwt.side.single]
  sidePaneSticky = true
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 2

[[menus.main]]
name = 'All Posts'
parent = 'Posts'
url = '/posts'
weight = 1

[[menus.main]]
name = 'Video Games'
parent = 'Posts'
url = '/tags/video-games'
weight = 2

[[menus.main]]
name = 'Ramblings'
parent = 'Posts'
url = '/tags/ramblings'
weight = 3

[[menus.main]]
name = 'Apocalypse TTRPG'
parent = 'Posts'
url = '/tags/apocalypse-ttrpg'
weight = 4

[[menus.main]]
name = 'Tags'
parent = 'Posts'
url = '/tags'
weight = 5

# [[menus.main]]
# name = 'Tags'
# url = '/tags'
# weight = 3

[[menus.main]]
name = 'About Me'
pageRef = '/about-me'
weight = 4

[[menus.main]]
name = 'Fellow Writers'
pageRef = '/fellow-writers'
weight = 5

# Parent menu item for "My Projects" dropdown
[[menus.main]]
name = 'My Projects'
identifier = 'projects'
weight = 6

# Child menu items under "My Projects"
[[menus.main]]
name = 'Media'
parent = 'projects'
pageRef = '/media'
weight = 1

#[[menus.main]]
#name = 'Tabletop'
#parent = 'projects'
#pageRef = '/tabletop'
#weight = 2

[[menus.main]]
name = 'Mods'
parent = 'projects'
pageRef = '/mods'
weight = 3

[[menus.main]]
name = 'Subscribe'
pageRef = '/newsletter'
weight = 7

# Build search index
[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

# This allows html coding to work on the website
 [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
