baseURL = "https://www.insignificantgamer.blog/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'rusty-typewriter'
[params.rtwt]
  sidePane = true
  countPageItems = 7

[params.rtwt.home]
  showBio = true
  showAuthorImg = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5

[params.rtwt.side.home]
  sidePaneSticky = false
  taxonomies = ['tags']
  countTaxonomy = 5

[params.rtwt.side.single]
  sidePaneSticky = true
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5

[[menus.main]]
name = 'RSS'
url = '/index.xml'
weight = 10
